//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihvati.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smeštaj.
        /// </summary>
        public static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smeštaj:.
        /// </summary>
        public static string Accommodation_ {
            get {
                return ResourceManager.GetString("Accommodation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena smeštaja.
        /// </summary>
        public static string Accommodation_rate {
            get {
                return ResourceManager.GetString("Accommodation_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smeštaji.
        /// </summary>
        public static string Accommodations {
            get {
                return ResourceManager.GetString("Accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Smeštaj.
        /// </summary>
        public static string Add_Accommodation {
            get {
                return ResourceManager.GetString("Add_Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj renovaciju.
        /// </summary>
        public static string Add_renovation {
            get {
                return ResourceManager.GetString("Add_renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saveti.
        /// </summary>
        public static string Advices {
            get {
                return ResourceManager.GetString("Advices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preporuke.
        /// </summary>
        public static string Advicess {
            get {
                return ResourceManager.GetString("Advicess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **(Potrebno je oceniti goste kako bi videli vaše ocene)**.
        /// </summary>
        public static string Attend {
            get {
                return ResourceManager.GetString("Attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pažnja: Imate neocenjene goste(rok za ocenu: 5 dana nakon iseljenja).
        /// </summary>
        public static string AttentionRate {
            get {
                return ResourceManager.GetString("AttentionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosečna ocena:.
        /// </summary>
        public static string Average_rate_ {
            get {
                return ResourceManager.GetString("Average_rate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži renovaciju.
        /// </summary>
        public static string Cancel_renovation {
            get {
                return ResourceManager.GetString("Cancel_renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkazano.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapacitet.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čistoća:.
        /// </summary>
        public static string Cleanliness_ {
            get {
                return ResourceManager.GetString("Cleanliness:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar:.
        /// </summary>
        public static string Comment_ {
            get {
                return ResourceManager.GetString("Comment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentariši.
        /// </summary>
        public static string Comnent {
            get {
                return ResourceManager.GetString("Comnent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi izveštaj.
        /// </summary>
        public static string Create_Report {
            get {
                return ResourceManager.GetString("Create_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbij.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje:.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj.
        /// </summary>
        public static string End_date {
            get {
                return ResourceManager.GetString("End_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj:.
        /// </summary>
        public static string EndDate_ {
            get {
                return ResourceManager.GetString("EndDate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objašnjene:.
        /// </summary>
        public static string Explanation_ {
            get {
                return ResourceManager.GetString("Explanation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poštovanje pravila:.
        /// </summary>
        public static string Following_rules_ {
            get {
                return ResourceManager.GetString("Following_rules:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna strana.
        /// </summary>
        public static string Home_page {
            get {
                return ResourceManager.GetString("Home_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atraktivne lokacjie gde je potreban novi smeštaj.
        /// </summary>
        public static string lab {
            get {
                return ResourceManager.GetString("lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija(grad).
        /// </summary>
        public static string Location_City_ {
            get {
                return ResourceManager.GetString("Location(City)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meni.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno dana.
        /// </summary>
        public static string Minimal_Days {
            get {
                return ResourceManager.GetString("Minimal_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesec.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesečna statistika.
        /// </summary>
        public static string Month_statistics {
            get {
                return ResourceManager.GetString("Month_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po mesecima.
        /// </summary>
        public static string Month_stats {
            get {
                return ResourceManager.GetString("Month_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najzauzetiji u:  .
        /// </summary>
        public static string Most_busy_in_ {
            get {
                return ResourceManager.GetString("Most_busy_in:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period najave.
        /// </summary>
        public static string Notice_Period {
            get {
                return ResourceManager.GetString("Notice_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Owner_Profile {
            get {
                return ResourceManager.GetString("Owner_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena vlasnika.
        /// </summary>
        public static string Owner_rate {
            get {
                return ResourceManager.GetString("Owner_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL slika.
        /// </summary>
        public static string Picture_URLs {
            get {
                return ResourceManager.GetString("Picture_URLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceni.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceni goste.
        /// </summary>
        public static string Rate_Guests {
            get {
                return ResourceManager.GetString("Rate_Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocenjivanje gostiju.
        /// </summary>
        public static string Rating_guest {
            get {
                return ResourceManager.GetString("Rating_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renoviraj.
        /// </summary>
        public static string Renovate {
            get {
                return ResourceManager.GetString("Renovate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renoviranje.
        /// </summary>
        public static string Renovating {
            get {
                return ResourceManager.GetString("Renovating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renoviranje.
        /// </summary>
        public static string Renovation {
            get {
                return ResourceManager.GetString("Renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavljen.
        /// </summary>
        public static string Reported {
            get {
                return ResourceManager.GetString("Reported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevi.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomereno.
        /// </summary>
        public static string Rescheduled {
            get {
                return ResourceManager.GetString("Rescheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeranje rezervacije.
        /// </summary>
        public static string Reservation_reschedule {
            get {
                return ResourceManager.GetString("Reservation_reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervisano.
        /// </summary>
        public static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje: Ova rezervacija se preklapa sa drugom rezervacijom.
        /// </summary>
        public static string ResheduleWarning {
            get {
                return ResourceManager.GetString("ResheduleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenzije.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titula:.
        /// </summary>
        public static string Role_ {
            get {
                return ResourceManager.GetString("Role:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošalji.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak.
        /// </summary>
        public static string Start_date {
            get {
                return ResourceManager.GetString("Start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak:.
        /// </summary>
        public static string StartDate_ {
            get {
                return ResourceManager.GetString("StartDate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smeštaj registrovan.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacije na kojima je potrebno zatvoriti smeštaj.
        /// </summary>
        public static string unlab {
            get {
                return ResourceManager.GetString("unlab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidi statistiku.
        /// </summary>
        public static string View_stats {
            get {
                return ResourceManager.GetString("View_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli u.
        /// </summary>
        public static string Welcome_to {
            get {
                return ResourceManager.GetString("Welcome_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  godini.
        /// </summary>
        public static string yearly {
            get {
                return ResourceManager.GetString("yearly", resourceCulture);
            }
        }
    }
}
